### ISSUE TITLE
Servers not using a domain don't get proxied

### ISSUE THREAD

**Issue by baduhai** [Molorius/bedrock-proxy#2]
If I point bedrock-proxy to a server behind a domain, it works but not when I point to an ip address directly. It'd be nice to do that, as I have a server that isn't behind a domain. I had a look through the code but I couldn't find what could possibly be preventing bedrock-proxy from working with ip addresses.

**Comment by Molorius** [comment]
I have been exclusively using this connected to direct IP addresses, do you have a public one you have unsuccessfully tried with?

**Comment by baduhai** [comment]
Interesting, it could be a problem on my end, since my internet connection has been sketchy all day. I do have an IP I have unsuccessfully tried with, but I don't exactly want to share it, since it's not a public server.

**Comment by Molorius** [comment]
Let me find a public one we can test on...

**Comment by Molorius** [comment]
I successfully tested 149.56.206.101 (play.cosmicpe.me) port 19132 with the bedrock-proxy compiled with gcc 10.2.0, running on an x64 computer with Arch Linux on kernel 5.10.7. The client was an Android 10 arm64 device running Bedrock v1.16.201.

**Comment by Molorius** [comment]
Sometimes networks are configured to not allow direct IP address traffic, perhaps that is your issue?

**Comment by Molorius** [comment]
While this doesn't directly answer your question, you may have an easier time with [phantom](https://github.com/jhead/phantom). I haven't tried it, but it looks like it does the same thing as my program. It has more contributors and looks overall better written.

**Comment by baduhai** [comment]
I'll do some more testing once my internet stabilises and get back to you. I'm also gonna work on a pull request to make it so you can input address and port as arguments when running bedrock-proxy, since I just don't think it makes sense to compile the program everytime you connect to a new server.

**Comment by baduhai** [comment]
> While this doesn't directly answer your question, you may have an easier time with [phantom](https://github.com/jhead/phantom). I haven't tried it, but it looks like it does the same thing as my program. It has more contributors and looks overall better written.

I have tried phantom, and it's very good, but I'm working on an android app that will proxy bedrock servers for consoles, just as your program does, but I'm having trouble creating java bindings for go packages. With your program I can use the android ndk and compile your code as a library for binding with java. Also I actually kind of understand what's going on with your program, but not with phantom, since I don't know a lick of go.

**Comment by Molorius** [comment]
I also know that bedrock-proxy works on other architectures, just so you are aware. I primarily use this on armv6, armv7, and armv8 devices running Debian Buster (Raspberry Pi 0/2/3 and Odroid C1/C2). A private version of this is running on esp8266, esp32, and esp32-s2 so it is not linux exclusive. 

bedrock-proxy has a bunch of bugs and is pretty messy code. I basically rewrote the whole thing a while back but I still need to clean up the newer version before pushing. Too busy with work and other projects.

**Comment by baduhai** [comment]
As you said, it does indeed work with ip addresses. Must've been my internet that was wonky yesterday.
